schema_version = "1.0.0"

id = "lodify_optimizer"
version = "2.0.1"
name = "LODify"
tagline = "全场景性能优化：贴图、减面与视窗管理"
maintainer = "小T_sune"
type = "add-on"
website = "https://github.com/XIAOTsune/LODify"


# Blender 插件通常使用 GPL-2.0-or-later 协议
license = ["SPDX:GPL-3.0-or-later"]

tags = ["3D View"]
blender_version_min = "4.2.0"

[permissions]

files = "用于读写贴图文件以进行缩放处理"
network = "仅用于打开在线文档"

[build]
paths = ["."]